return {
	{name = "iron-plate", count = 1000},
	{name = "copper-plate", count = 600},
	{name = "coal", count = 1000},
	{name = "iron-gear-wheel", count = 1000},
	{name = "electronic-circuit", count = 600},
	{name = "inserter", count = 100},
	{name = "transport-belt", count = 1000},
	{name = "straight-rail", count = 1000},
	{name = "train-stop", count = 10},
	{name = "rail-signal", count = 50},
	{name = "rail-chain-signal", count = 50},
	{name = "locomotive", count = 4},
	{name = "cargo-wagon", count = 12},
	{name = "rail", count = 1000},
}
